################################################################################
# EKS Dev Test Deployment
#
# > ⚠️ AI-Generated Deployment
# > Generated by Bob, an AI assistant powered by IBM watsonx.
# > Review before applying to production.
################################################################################

terraform {
  required_version = ">= 1.5.7"

  cloud {
    organization = "jose-merchan"
    workspaces {
      name = "eks-dev-test"
    }
  }

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.35"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

################################################################################
# EKS Cluster — private registry module
# NOTE: aws-ebs-csi-driver addon is excluded here; it is added below after
#       the OIDC provider is known (IRSA dependency ordering).
################################################################################

module "eks_cluster" {
  source  = "app.terraform.io/jose-merchan/eks-cluster/aws"
  version = "~> 0.0.2"

  # Mandatory tags
  environment = var.environment
  owner       = var.owner
  cost_center = var.cost_center
  project     = var.project

  # Cluster
  cluster_name       = "${var.project}-${var.environment}"
  kubernetes_version = "1.33"

  # Keep API server private — only reachable from within the VPC
  endpoint_public_access = false
  enable_irsa            = true
  log_retention_days     = 90

  # Dev-sized single node group
  node_groups = {
    dev = {
      instance_types = ["t3.medium"]
      capacity_type  = "ON_DEMAND"
      min_size       = 1
      max_size       = 3
      desired_size   = 1
      disk_size_gb   = 50
    }
  }

  # New VPC — eu-central-1 has 3 AZs
  availability_zones     = ["${var.aws_region}a", "${var.aws_region}b", "${var.aws_region}c"]
  vpc_cidr               = "10.0.0.0/16"
  private_subnet_cidrs   = ["10.0.0.0/19", "10.0.32.0/19", "10.0.64.0/19"]
  public_subnet_cidrs    = ["10.0.128.0/20", "10.0.144.0/20", "10.0.160.0/20"]
  enable_internet_access = true
  single_nat_gateway     = true # single NAT saves cost in dev

  # Override addons: exclude aws-ebs-csi-driver — it is installed below
  # after the IRSA role has been created (dependency ordering fix)
  addons = {
    coredns = { most_recent = true }
    kube-proxy = { most_recent = true }
    vpc-cni = { most_recent = true, before_compute = true }
  }
}

################################################################################
# IRSA Role for EBS CSI Driver
# Must be created AFTER module.eks_cluster so the OIDC provider ARN is known.
# See: https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html
################################################################################

resource "aws_iam_role" "ebs_csi_driver" {
  name_prefix = "${var.project}-${var.environment}-ebs-csi-"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Principal = {
        Federated = module.eks_cluster.oidc_provider_arn
      }
      Action = "sts:AssumeRoleWithWebIdentity"
      Condition = {
        StringEquals = {
          "${module.eks_cluster.oidc_provider}:sub" = "system:serviceaccount:kube-system:ebs-csi-controller-sa"
          "${module.eks_cluster.oidc_provider}:aud" = "sts.amazonaws.com"
        }
      }
    }]
  })

  tags = {
    Environment = var.environment
    Owner       = var.owner
    CostCenter  = var.cost_center
    Project     = var.project
    ManagedBy   = "Terraform"
  }
}

resource "aws_iam_role_policy_attachment" "ebs_csi_driver" {
  role       = aws_iam_role.ebs_csi_driver.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicyV2"
}

################################################################################
# EBS CSI Driver addon — installed after IRSA role is ready
################################################################################

resource "aws_eks_addon" "ebs_csi_driver" {
  cluster_name             = module.eks_cluster.cluster_name
  addon_name               = "aws-ebs-csi-driver"
  addon_version            = null # use most recent
  resolve_conflicts_on_create = "NONE"
  resolve_conflicts_on_update = "OVERWRITE"
  service_account_role_arn = aws_iam_role.ebs_csi_driver.arn
  preserve                 = true

  timeouts {
    create = "30m"
    update = "30m"
    delete = "30m"
  }

  tags = {
    Environment = var.environment
    Owner       = var.owner
    CostCenter  = var.cost_center
    Project     = var.project
    ManagedBy   = "Terraform"
  }

  depends_on = [aws_iam_role_policy_attachment.ebs_csi_driver]
}

################################################################################
# Kubernetes provider — authenticates using the new cluster's outputs
################################################################################

provider "kubernetes" {
  host                   = module.eks_cluster.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks_cluster.cluster_certificate_authority_data)

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    args = [
      "eks", "get-token",
      "--cluster-name", module.eks_cluster.cluster_name,
      "--region", var.aws_region,
    ]
  }
}

################################################################################
# Test web application — NGINX served via AWS NLB (internet-facing)
################################################################################

resource "kubernetes_namespace" "test_app" {
  metadata {
    name = "test-app"
    labels = {
      environment = var.environment
      owner       = var.owner
      project     = var.project
    }
  }

  depends_on = [module.eks_cluster]
}

resource "kubernetes_deployment" "nginx" {
  metadata {
    name      = "nginx"
    namespace = kubernetes_namespace.test_app.metadata[0].name
    labels = {
      app         = "nginx"
      environment = var.environment
    }
  }

  spec {
    replicas = 2

    selector {
      match_labels = {
        app = "nginx"
      }
    }

    template {
      metadata {
        labels = {
          app         = "nginx"
          environment = var.environment
        }
      }

      spec {
        container {
          name  = "nginx"
          image = "public.ecr.aws/nginx/nginx:1.27-alpine"

          port {
            container_port = 80
          }

          resources {
            requests = {
              cpu    = "50m"
              memory = "64Mi"
            }
            limits = {
              cpu    = "100m"
              memory = "128Mi"
            }
          }

          # Custom welcome page that confirms the deployment is Bob-generated
          volume_mount {
            name       = "html"
            mount_path = "/usr/share/nginx/html"
          }
        }

        # Inline ConfigMap volume with custom HTML
        volume {
          name = "html"
          config_map {
            name = kubernetes_config_map.nginx_html.metadata[0].name
          }
        }
      }
    }
  }

  depends_on = [kubernetes_namespace.test_app]
}

resource "kubernetes_config_map" "nginx_html" {
  metadata {
    name      = "nginx-html"
    namespace = kubernetes_namespace.test_app.metadata[0].name
  }

  data = {
    "index.html" = <<-HTML
      <!DOCTYPE html>
      <html>
        <head><title>EKS Dev Test</title></head>
        <body style="font-family:sans-serif;text-align:center;padding:60px;background:#f0f4f8">
          <h1>✅ EKS cluster is live!</h1>
          <p>Environment: <strong>${var.environment}</strong></p>
          <p>Project: <strong>${var.project}</strong></p>
          <p>Region: <strong>${var.aws_region}</strong></p>
          <p><em>Generated by Bob — IBM watsonx AI assistant</em></p>
        </body>
      </html>
    HTML
  }

  depends_on = [kubernetes_namespace.test_app]
}

# Internet-facing Network Load Balancer — exposes port 80 to the internet
resource "kubernetes_service" "nginx" {
  metadata {
    name      = "nginx"
    namespace = kubernetes_namespace.test_app.metadata[0].name
    annotations = {
      # AWS NLB (faster provisioning than Classic ELB)
      "service.beta.kubernetes.io/aws-load-balancer-type"   = "nlb"
      "service.beta.kubernetes.io/aws-load-balancer-scheme" = "internet-facing"
    }
  }

  spec {
    selector = {
      app = "nginx"
    }

    type = "LoadBalancer"

    port {
      port        = 80
      target_port = 80
      protocol    = "TCP"
    }
  }

  depends_on = [kubernetes_deployment.nginx]
}
